In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3,3,1], [6,8,11,10,7]])
a = np.transpose(a)
print(a.shape)
a

(5, 2)


array([[ 2,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_col_1 = np.mean(a[:,0])
print(mean_col_1)

2.0


In [4]:
mean_col_2 = np.mean(a[:,1])
print(mean_col_2)

8.4


In [5]:
mean_a = np.array([[mean_col_1,mean_col_2]])
print(mean_a.shape)
mean_a

(1, 2)


array([[2. , 8.4]])

In [6]:
a_centered = a-mean_a
print(a_centered.shape)
a_centered

(5, 2)


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
temp1 = a_centered[:,0]
temp1

array([-1.,  0.,  1.,  1., -1.])

In [8]:
temp2 = a_centered[:,1]
temp2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = np.dot(temp1,temp2)
a_centered_sp

8.0

In [10]:
rescovar = a_centered_sp / (len(temp1)-1)
rescovar

2.0

In [11]:
covar_matr= np.cov(np.transpose(a))
covar_matr

array([[1. , 2. ],
       [2. , 4.3]])

In [12]:
covar_task4 = covar_matr[0][1] 
covar_task4 

2.0